### ISSUE TITLE
Getting IndexError  when running BCC with Emotions dataset

### ISSUE THREAD

**Issue by SachiniEMSPE** [jona2510/PGM_PyLib#2]
Hi,  Thank you so much for your great work! I was able to run exampleBCC.py and tried to use it with the [Emotions ](https://www.openml.org/d/41465) dataset (following [Bayesian Chain Classifier for Multidimensional Classification](https://www.aaai.org/ocs/index.php/IJCAI/IJCAI11/paper/viewFile/3246/3811)).  My code is as below. 
```
dataset = fetch_openml(name='emotions', as_frame=True)
X = dataset.data 
Y = dataset.target 

list_cols = list(Y.columns[Y.dtypes!=float])
for column in list_cols:
    Y[column] = Y[column].astype('category').cat.codes[:]

df_features_file= X
df_variables_file= Y
F = df_features_file.values 
X = df_variables_file.values
Xtrain, Xtest, ytrain, ytest = train_test_split(F,X, test_size = 0.3,random_state=0) 

# create the classifiers 
c = bcc.BCC(chainType="parents", baseClassifier=nb.naiveBayes(), structure="auto")
# train the classifier
c.fit(Xtrain, ytrain)
# predict 
p = c.predict(Xtest)
# evaluation
print(c.exactMatch(ytest, p))
```
However, I'm getting an index error as attached below. 
![image](https://user-images.githubusercontent.com/48669988/147128685-a6bf0570-6101-4229-991d-236621693c55.png)

I tried with another dataset as well, I'm getting the same error here in `NaiveBayes.py `. 
![image](https://user-images.githubusercontent.com/48669988/147129236-abff1981-fe91-431b-8802-ef10f50aaec7.png)

I was wondering if you could help me with this. Thank you!

**Comment by jona2510** [comment]
Hello,

The classifier 'nb.naiveBayes' only works for datasets with **categorical** attributes/features. 
The emotions dataset has **numeric** attributes, therefore, the naive Bayes classifier will not work properly. 

I recommend replacing naive bayes classifier with Gaussian naive bayes classifier, that is able to handle numeric attributes:


> from PGM_PyLib.naiveBayes import GaussianNaiveBayes as gnbc
c = bcc.BCC(chainType="parents", baseClassifier=gnbc(smooth=0.1, usePrior=True), structure="auto")

Moreover, you can use external classifiers, for example a support vector machine:

> from sklearn.svm import SVC
c = bcc.BCC(chainType="parents", baseClassifier=SVC(), structure="auto")

Regards

**Comment by SachiniEMSPE** [comment]
I see. I tried both options. Now it works well. Thank you so much for your help!
